version: "3.9"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.testing
    env_file: .env
    stdin_open: false
    volumes:
      - .:/app
    networks:
      - wearemo
    ports:
      - "8000:8000"
      - "5551:5555"
    depends_on:
      - db



  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev-db-data-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wearemo

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5001:80"
    networks:
      - wearemo
    restart: unless-stopped

networks:
  wearemo:
    driver: bridge

volumes:
  dev-db-data-test:
  pgadmin:
